name: reconstructed-env
channels:
- conda-forge
- defaults
dependencies:
- conda-forge::cffi==1.17.1
- conda-forge::charset-normalizer==3.4.1
- conda-forge::cloudpickle==3.1.1
- conda-forge::colorama==0.4.6
- conda-forge::conda-pack==0.8.1
- conda-forge::idna==3.10
- conda-forge::markdown-it-py==3.0.0
- conda-forge::ndcctools==7.15.1
- conda-forge::packaging==24.2
- conda-forge::pip==25.0.1
- conda-forge::pygments==2.19.1
- conda-forge::pytest==8.3.5
- conda-forge::rich==14.0.0
- conda-forge::setuptools==78.1.0
- pip==25.0.1
- python==3.13.3
- pip:
  - anyio==4.9.0
  - arrow==1.3.0
  - asttokens==3.0.0
  - attrs==25.3.0
  - babel==2.17.0
  - black==25.1.0
  - comm==0.2.2
  - cycler==0.12.1
  - debugpy==1.8.14
  - defusedxml==0.7.1
  - executing==2.2.0
  - fastjsonschema==2.21.1
  - flask==3.1.1
  - floability==0.1.1
  - fonttools==4.58.0
  - fqdn==1.5.1
  - httpx==0.28.1
  - ipyflow==0.0.209
  - ipykernel==6.29.5
  - ipython-pygments-lexers==1.1.1
  - ipython==9.1.0
  - ipywidgets==8.1.6
  - isoduration==20.11.0
  - jedi==0.19.2
  - jinja2==3.1.6
  - json5==0.12.0
  - jsonschema-specifications==2024.10.1
  - jsonschema==4.23.0
  - jupyter-client==8.6.3
  - jupyter-console==6.6.3
  - jupyter-core==5.7.2
  - jupyter-events==0.12.0
  - jupyter-lsp==2.2.5
  - jupyter-server==2.15.0
  - jupyterlab==4.4.0
  - kishu==0.3.3
  - kiwisolver==1.4.8
  - matplotlib-inline==0.1.7
  - matplotlib==3.10.3
  - nbclassic==1.3.1
  - nbclient==0.10.2
  - nbconvert==7.16.6
  - nbformat==5.10.4
  - networkx==3.4.2
  - nltk==3.9.1
  - notebook==7.4.0
  - numpy==2.2.4
  - pandas==2.2.3
  - parso==0.8.4
  - pbr==6.1.1
  - platformdirs==4.3.7
  - prompt-toolkit==3.0.51
  - psutil==7.0.0
  - pure-eval==0.2.3
  - pyccolo==0.0.71
  - pyparsing==3.2.3
  - qiskit==2.0.0
  - referencing==0.36.2
  - send2trash==1.8.3
  - shortuuid==1.0.13
  - stack-data==0.6.3
  - stevedore==5.4.1
  - sympy==1.14.0
  - tornado==6.4.2
  - tqdm==4.67.1
  - traitlets==5.14.3
  - typer==0.15.3
  - uri-template==1.3.0
  - wcwidth==0.2.13
  - webcolors==24.11.1
  - websocket-client==1.8.0
  - wheel==0.45.1
