name: reconstructed-env
channels:
- conda-forge
- defaults
dependencies:
- conda-forge::awkward-cpp==45
- conda-forge::awkward==2.8.1
- conda-forge::bokeh==3.7.2
- conda-forge::boost-histogram==1.5.2
- conda-forge::cachetools==5.5.2
- conda-forge::cffi==1.17.1
- conda-forge::cloudpickle==3.1.1
- conda-forge::coffea==2024.4.1
- conda-forge::colorama==0.4.6
- conda-forge::conda-pack==0.8.1
- conda-forge::correctionlib==2.6.4
- conda-forge::cytoolz==1.0.1
- conda-forge::dask-awkward==2024.3.0
- conda-forge::dask-histogram==2024.3.0
- conda-forge::dask==2024.4.2
- conda-forge::distributed==2024.4.2
- conda-forge::fonttools==4.57.0
- conda-forge::fsspec==2025.3.2
- conda-forge::hist==2.8.0
- conda-forge::histoprint==2.6.0
- conda-forge::jinja2==3.1.6
- conda-forge::llvmlite==0.44.0
- conda-forge::lz4==4.3.3
- conda-forge::markdown-it-py==3.0.0
- conda-forge::markupsafe==3.0.2
- conda-forge::ndcctools==7.15.1
- conda-forge::numba==0.61.2
- conda-forge::numpy==1.26.4
- conda-forge::packaging==24.2
- conda-forge::pandas==2.2.3
- conda-forge::pip==25.0.1
- conda-forge::psutil==7.0.0
- conda-forge::pyarrow==19.0.1
- conda-forge::pycparser==2.22
- conda-forge::pygments==2.19.1
- conda-forge::pytz==2025.2
- conda-forge::rich==14.0.0
- conda-forge::scipy==1.15.2
- conda-forge::setuptools==78.1.0
- conda-forge::tblib==3.1.0
- conda-forge::toolz==1.0.0
- conda-forge::tornado==6.4.2
- conda-forge::tqdm==4.67.1
- conda-forge::uhi==0.5.0
- conda-forge::uproot==5.6.0
- conda-forge::wheel==0.45.1
- conda-forge::xxhash==0.8.3
- conda-forge::yaml==0.2.5
- conda-forge::zstandard==0.23.0
- pip==25.0.1
- python==3.12.10
- pip:
  - asttokens==3.0.0
  - comm==0.2.2
  - debugpy==1.8.14
  - executing==2.2.0
  - fastjet==3.4.2.1
  - ipykernel==6.29.5
  - ipython-pygments-lexers==1.1.1
  - ipython==9.1.0
  - jedi==0.19.2
  - jsonschema==4.23.0
  - jupyter-client==8.6.3
  - jupyter-core==5.7.2
  - matplotlib-inline==0.1.7
  - nbformat==5.10.4
  - parso==0.8.4
  - platformdirs==4.3.7
  - prompt-toolkit==3.0.51
  - pure-eval==0.2.3
  - stack-data==0.6.3
  - traitlets==5.14.3
  - vector==1.6.1
  - wcwidth==0.2.13
