name: cesm-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ndcctools
  - cloudpickle=3.1.0
  - packaging=24.2
  - aiobotocore=2.20.0
  - aiofiles=24.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.9.5
  - aioitertools=0.12.0
  - aiosignal=1.3.1
  - fsspec=2025.3.2
  - s3fs=2025.3.2
  - yarl=1.9.11
  - requests=2.32.3
  - pandas=2.2.3
  - xarray=2025.3.1
  - xarray-regrid=0.4.0
  - xesmf=0.8.8
  - xhistogram=0.3.2
  - xskillscore=0.0.26
  - netcdf4=1.7.2
  - h5netcdf=1.5.0
  - h5py=3.12.1
  - rasterio=1.4.3
  - zarr=2.18.3
  - numpy_groupies=0.11.3
  - bottleneck=1.4.2
  - scipy=1.14.1
  - scikit-learn=1.6.1
  - statsmodels=0.14.4
  - numba=0.61.0
  - numbagg=0.9.0
  - llvmlite=0.44.0
  - dask=2025.3.0
  - distributed=2025.3.0
  - dask-expr=2.0.0
  - dask-jobqueue=0.9.0
  - zict=3.0.0
  - geopandas=1.0.1
  - odc-geo=0.4.8
  - odc-stac=0.3.10
  - pyogrio=0.10.0
  - pyproj=3.7.0
  - shapely=2.0.6
  - eofs=2.0.0
  - metpy=1.6.3
  - matplotlib=3.9.3
  - seaborn=0.13.2
  - bokeh=3.6.1
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - ipywidgets=8.1.6
  - jupyterlab_widgets=3.0.14
  - widgetsnbextension=4.0.14
  - debugpy=1.8.9
  - attrs=23.2.0
  - cachetools=5.5.0
  - psutil=6.1.0
  - tqdm=4.67.1
  - toolz=1.0.0
  - pyyaml=6.0.2
  - flake8
  - gdb
  - clang-format
  - cf-units=3.3.0
  - cf_xarray=0.10.0
  - flox=0.10.0
  - properscoring=0.1
  - ecgtools=2024.7.31
  - appdirs=1.4.4
  - comm=0.2.2
  - charset-normalizer=3.4.0
  - idna=3.10
  - urllib3=2.2.3
  - six=1.16.0
  - pytz=2024.2
  - python-dateutil=2.9.0.post0
  - markupsafe=3.0.2
  - jinja2=3.1.4
  - decorator=5.1.1
  - executing=2.1.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - fasteners=0.19
  - contourpy=1.3.1
  - cycler=0.12.1
  - fonttools=4.55.0
  - frozenlist=1.4.1
  - jedi=0.19.2
  - jmespath=1.0.1
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - kiwisolver=1.4.7
  - locket=1.0.0
  - lxml=5.3.2
  - lz4=4.3.3
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numcodecs=0.13.1
  - opt_einsum=3.4.0
  - parso=0.8.4
  - partd=1.4.2
  - pexpect=4.9.0
  - pillow=11.0.0
  - pint=0.24.4
  - platformdirs=4.3.6
  - pooch=1.8.2
  - propcache=0.2.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=18.1.0
  - pydantic=2.10.2
  - pydantic-core=2.27.1
  - pyparsing=3.2.0
  - referencing=0.36.1
  - rpds-py=0.22.3
  - sparse=0.15.5
  - tblib=3.0.0
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - wcwidth=0.2.13
  - wrapt=1.17.2
  - zipp=3.21.0
  - gnuplot
  - pip:
      - pelicanfs==1.1.2
      - aiowebdav==0.1.0rc5
      - stack-data==0.6.3
